### PR TITLE
Add Web Support

### PR DESCRIPTION
**Pull request by nandorojo**
This PR adds improved Web support.

### Changes

- [x] Add option to disable path transitions, since these flicker on Web (see #8).
- [x] Document Web support, and mark it as experimental.
- [x] Fix `CursorLine`
- [ ] `ReText` doesn't work on web. I don't think this is blocking, but I do want to figure out why. I think it's because you can't pass both animated style _and_ `animatedProps` to Reanimated components on Web (see https://github.com/software-mansion/react-native-reanimated/issues/1808#issuecomment-907878379).

### Extra

I also added a `.prettierrc.js` file, since my IDE wouldn't use the proper Prettier config without this.

~The only open problem left with Web support, as mentioned at #8, is that the `CursorLine` has an incorrect vertical placement. But I think this can be a separate PR.~ (added)

~PS Seems like I accidentally pulled in changes from #6 into this PR too...let me know if I need to remove those. But it's just one line.~ (merged)

### Sidenote

Also, it seems like some of the formatting from my end got changed on the `README.md`, presumably because your IDE had a different Prettier config than the one in `package.json`. My VSCode auto-formats on save, so I think it changed some of the spacing on the README. If we want to change this back, we can edit the Prettier config in `package.json` to match your local IDE's.

### CODE REVIEW

**Comment by jxom** [comment]
Thank you!!

**Comment by nandorojo** [comment]
Looks like the ReText issue is a bug in Reanimated. I mentioned in on a Reanimated issue here: https://github.com/software-mansion/react-native-reanimated/issues/1808#issuecomment-938211589

Relevant discussion on `react-native-redash`: https://github.com/wcandillon/react-native-redash/issues/453#issuecomment-938207575

**Comment by nandorojo** [comment]
Okay, so I was able to patch the `ReText` issue like so:

```tsx
const inputRef = React.useRef(null)

useAnimatedReaction(
  () => {
    return text.value
  },
  (data, prevData) => {
    if (Platform.OS === 'web' && data !== prevData && inputRef.current) {
      inputRef.current.setNativeProps({
        value: data
      })
    }
  }
)
```

I'll probably implement this myself in a custom `ReText` component, unless we want to add this to the lib directly.

**Comment by jxom** [comment]
I'm happy to have our own reanimated text component. Is the above code utilising `TextInput`, or `ReText`?

**Comment by nandorojo** [comment]
@jxom will you implement this, or should I PR?

**Comment by jxom** [comment]
Up to you. If you feel like it, then go for it. Otherwise, I'll look into this later today or on the weekend. :)

**Comment by nandorojo** [comment]
One thing: on Web, you can't use _both_ `useAnimatedStyle` and `useAnimatedProps` on the same component. It seems like the library never uses both props at once anyway, but just something to keep in mind for future reference.

**Comment by nandorojo** [comment]
Opened PR at https://github.com/coinjar/react-native-wagmi-charts/pull/10

**Pull request merged**
