### PR TITLE
Add `LineChart.Highlight` & refactor `LineChart.Dot`

### PR DESCRIPTION
**Pull request by jxom**
### Highlighted paths (`LineChart.Highlight`)

This PR essentially adds the ability to add a highlight to a section of a path. This addresses #46.

```
<LineChart.Provider data={data}>
  <LineChart>
    <LineChart.Path>
      <LineChart.Highlight color="red" from={10} to={15} />
    </LineChart.Path>
  </LineChart>
</LineChart.Provider>
```

Screen Shot 2021-11-23 at 11 54 02 am

### Breaking change: `LineChart.Dot` refactor

I have decided that maybe `LineChart.Dot` should not be pulseable by default. I think this should rather be opt in? 
I ended up breaking up the `outerPulse` prop into two separate props: `hasPulse` and `pulseBehaviour`. The prop `hasPulse` acts as a **simple** toggle to turn the pulse feature on, and the prop `pulseBehaviour` acts as an enum to control the behaviour of the pulse (whether it be active during interaction or not – aka. `"always"` & `"while-inactive"`).
I also noticed at the moment, that if `outerPulse` is set to `"never"`, that the outer circle is there by default. I also reckon this should be opt-in, so I added a `hasOuterDot` toggle to enable this (however, if `hasPulse` is truthy, `hasOuter` will always be truthy too).

### Other changes

- Refactored the documentation to be separated by chart type (instead of feature), to be more comprehensive, as I think people who want to look at line chart docs don't want to be looking at candlestick docs at the same time.
- Separated the functions in `utils.ts` files into their own files, as it is starting to get a bit large.

### CODE REVIEW

**Comment by jxom** [comment]
@nandorojo – wouldn't mind your thoughts on this.

**Comment by nandorojo** [comment]
One thing I like about the Robinhood charts is that it lets you highlight/lowlight different sections based on where your cursor is

**Comment by jxom** [comment]
Interesting, can you provide an example of this? Robinhood isn't available in my country :( 

I reckon we could easily start with this, and iterate on it though.

**Comment by nandorojo** [comment]
https://user-images.githubusercontent.com/13172299/142970589-68e6ffe1-4335-4ddb-8292-efb5ed4837ce.MOV

Agreed, see that video for reference

**Pull request merged**
