### PR TITLE
Fix LineChart.Cursor snapToPoint crash

### PR DESCRIPTION
**Pull request by cam-shaw**
**Before PR**

https://github.com/coinjar/react-native-wagmi-charts/assets/6579750/cfb0d5b3-843b-4b26-bb3d-1ab102936bbc

**After PR**

https://github.com/coinjar/react-native-wagmi-charts/assets/6579750/7708b79b-0187-4852-97cf-c613fd34ad5b

### CODE REVIEW

**Comment by arancauchi** [comment]
Looks great, I believe there's just one merge conflict to fix and then I can merge :)

**Comment by LeoAnt02** [comment]
@cam-shaw Any update with this ?

**Comment by cam-shaw** [comment]
@arancauchi @LeoAnt02 PR has been updated to resolve conflicts.

**Comment by LeoAnt02** [comment]
@cam-shaw what version of expo this is for btw ? v48 - v49 ? Is this tested on web v49 ? (Webpack / the new metro bundler for web)

**Comment by cam-shaw** [comment]
@LeoAnt02 this was against Expo 48. However, it's worth noting that it seems the web example project seems to be broken so your mileage may vary as I don't have an Expo web project to test against.
I had to go back to version 2.0.0 to get the example web project up and running.

**Comment by cam-shaw** [comment]
There is this PR that updates to Expo 49, so if that interests you it could be worth working with this dev to ensure web compatibility with Expo 49 https://github.com/coinjar/react-native-wagmi-charts/pull/149

**Comment by barrymichaeldoyle** [comment]
Looking forward to seeing this one released :)

**Pull request merged**
