### PR TITLE
Chore: Compatibility of RN 0.74 and Expo SDK 51

### PR DESCRIPTION
**Pull request by alantoa**
## Why 

During our project upgrade to expo sdk 51 and RN 0.74, i noticed that this lib some types are outdated with Reanimated and RN. 
This PR is compatible with the latest versions of Expo and RN.

## How 
- Replacing Animated.SharedValue with SharedValue directly because renimated is deprecated with an old type.

- During testing the example project, I noticed that many configurations and libraries in the project are already outdated. For instance, the app.json configuration is already out of date. You can refer to the latest documentation [here](https://github.com/expo/fyi/blob/main/root-expo-object.md) for instructions on updating it. 

- And now I'm using Yarn 3 to integrate example and library code. It's simple and doesn't rely on too much configuration.

## Test 

I have tested the web and iOS app, and they all work well.

https://github.com/coinjar/react-native-wagmi-charts/assets/37520667/deafa421-1070-4ed3-9f3e-52f242e59927 

Let me know if you guys have any questions about this PR!

### CODE REVIEW

**Comment by nandorojo** [comment]
Looks good to me.

**Comment by honeybadger26** [comment]
Nicely done! Thanks @alantoa

**Comment by alantoa** [comment]
Hey @honeybadger26, could you please release it on npm? I noticed that it's available on GitHub but not on npm... 

CleanShot 2024-05-21 at 21 23 27@2x

**Comment by honeybadger26** [comment]
Hi @alantoa. There were a few TypeScript errors that prevented the build (and publish) of the package. I aim to fix those and get a release out as soon as I can.

**Comment by honeybadger26** [comment]
@alantoa v2.5.1 has been released to npm :)

**Comment by alantoa** [comment]
@honeybadger26  thank you! 🙏

**Pull request merged**
